### PR TITLE
resolved #5 Swift package

### LINKED ISSUE #5: Update to Swift 5.1 and add SwiftPM support
- Update to Swift 5.1
- Add SwiftPM support

### PR DESCRIPTION
**Pull request by ftp27**
Unfortunately, Xcode project generates a little tricky but it will work

### CODE REVIEW

**Comment by ftp27** [comment]
I think it's too many changes just for one package file. I'll try to do it shorter

**Comment by ftp27** [comment]
Perfect. It works)

**Comment by pedrommcarrasco** [comment]
Thank you for your contribution @ftp27!
Could you also update the `README.md` to include SwiftPM?

**Comment by ftp27** [comment]
@pedrommcarrasco here you are

**Comment by pedrommcarrasco** [comment]
Great job @ftp27! Thanks for helping! ❤️

**Pull request merged**
