### PR TITLE
Add shared scheme for project

### PR DESCRIPTION
**Pull request by alspirichev**
Hi!

I fixed issue with shared scheme as part of Hacktoberfest.

### CODE REVIEW

**Comment by pedrommcarrasco** [comment]
Hey @alspirichev! 👋 
Thanks for helping! Did you test this? Also can you update the podspec version by a patch? Going to release a version once this gets merged.

**Comment by pedrommcarrasco** [comment]
This fixes #7

**Comment by alspirichev** [comment]
Yes, I tested it on my pet-project.
I also updated podspec version.

**Comment by pedrommcarrasco** [comment]
Great, looks go to me 👍 
Thanks for helping @alspirichev! 🙌

**Pull request merged**
